/**
 * AU-5: generates the Keycloak login theme `datahub` from branding.json, so the white-label look continues
 * after the redirect. Output: aspire/DataHub.AppHost/keycloak/themes/datahub/login (bind-mounted by the AppHost).
 * Run: `bun run keycloak-theme` (BRANDING_FILE and MINIO_PUBLIC_URL are honoured). Keycloak picks up a new theme on restart.
 */
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { googleFontsUrl, parseBranding, resolveAsset } from "../src/lib/branding";

const web = fileURLToPath(new URL("..", import.meta.url));
const file = path.resolve(web, process.env.BRANDING_FILE ?? "config/branding.json");
const branding = parseBranding(JSON.parse(readFileSync(file, "utf8")), file);
const out = path.resolve(web, "../aspire/DataHub.AppHost/keycloak/themes/datahub/login");

rmSync(out, { recursive: true, force: true });
mkdirSync(path.join(out, "resources/css"), { recursive: true });
mkdirSync(path.join(out, "resources/img"), { recursive: true });

/** Local /public assets are copied into the theme; URLs (and s3:// objects) are referenced as-is. */
function asset(src: string, name: string): string {
  if (src.startsWith("/")) {
    const target = `${name}${path.extname(src)}`;
    copyFileSync(path.join(web, "public", src), path.join(out, "resources/img", target));
    return `../img/${target}`;
  }
  return resolveAsset(src);
}

const p = branding.palette.light;
const { background, overlay } = branding.authScreen;
const fonts = googleFontsUrl(branding);
const logo = asset(branding.logo, "logo");
const bg =
  background.type === "image"
    ? `url("${asset(background.src, "background")}") center / cover no-repeat`
    : background.src;
const alpha = Math.round(overlay.opacity * 255)
  .toString(16)
  .padStart(2, "0");

const css = `/* Generated from ${path.relative(path.resolve(web, ".."), file)} by web/scripts/keycloak-theme.ts. Do not edit. */
${fonts ? `@import url("${fonts}");\n` : ""}:root {
  --pf-v5-global--primary-color--100: ${p.primary};
  --pf-v5-global--primary-color--200: ${p.primary};
  --pf-v5-global--link--Color: ${p.primary};
  --pf-v5-global--link--Color--hover: ${p.primary};
  --pf-v5-global--danger-color--100: ${p.error};
  --pf-v5-global--success-color--100: ${p.success};
  --pf-v5-global--Color--100: ${p.foreground};
  --pf-v5-global--BackgroundColor--100: ${p.background};
  --pf-v5-global--FontFamily--text: "${branding.fonts.body.family}", system-ui, sans-serif;
  --pf-v5-global--FontFamily--heading: "${branding.fonts.heading.family}", system-ui, sans-serif;
}
body, .pf-v5-c-login {
  background: linear-gradient(${overlay.color}${alpha}, ${overlay.color}${alpha}), ${bg};
  font-family: var(--pf-v5-global--FontFamily--text);
}
.pf-v5-c-login__main { background-color: ${p.background}; color: ${p.foreground}; border-radius: 8px; }
.pf-v5-c-login__main-header h1, .pf-v5-c-title { font-family: var(--pf-v5-global--FontFamily--heading); }
.pf-v5-c-button.pf-m-primary { background-color: ${p.primary}; color: ${p.onPrimary}; }
#kc-header-wrapper {
  font-family: var(--pf-v5-global--FontFamily--heading);
  color: #fff;
  font-size: 0;
  background: url("${logo}") center top / 56px 56px no-repeat;
  padding-top: 64px;
}
#kc-header-wrapper::after { content: "${branding.name.replace(/"/g, '\\"')}"; font-size: 1.75rem; font-weight: 600; }
`;

writeFileSync(path.join(out, "resources/css/datahub.css"), css);
writeFileSync(
  path.join(out, "theme.properties"),
  `# Generated by web/scripts/keycloak-theme.ts from branding.json. Do not edit.
parent=keycloak.v2
import=common/keycloak
styles=css/styles.css css/datahub.css
darkMode=false
`,
);
console.info(`keycloak theme written to ${path.relative(web, out)} (${branding.name})`);
