<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\DataHub.Application\DataHub.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Keycloak.Authentication" />
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DataHub.Auth.Tests" />
  </ItemGroup>
</Project>
